### ISSUE TITLE
Create the project and research technologies

### ISSUE THREAD

**Issue by HabakukBeneke** [HabakukBeneke/Website#1]
**Task Description**
We need to create the project and research which technologies and stack we want to use. We need to decide if we want to use SSR (Server-Side Rendering) and whether we want to implement SCSS or not. We should also consider the advantages and disadvantages of each option and decide if we want to develop a backend or if everything will be frontend.

**Objective**
The objective of this task is to set up the project foundation and determine the technologies and stack to be used.

**Requirements**

- [x] Create the project.
- [x] Research technologies and stack.
- [x] Decide on the use of SSR.
- [x] Decide on the implementation of SCSS.
- [x] Evaluate the advantages and disadvantages of the selected technologies.
- [x] Decide if there will be a backend or if everything will be frontend.

**Acceptance Criteria**
To consider the task complete, we must create the project and set up the basic configuration.
